name: Update html                

on: push

jobs:   
  build:
    runs-on: ubuntu-latest
    container: pschaus/sphinx-java
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8                         
      uses: actions/setup-python@v2
      with:
        python-version: 3.8                         
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate html
      run: |
        cd userguide
        make html
        cp -r build/html/* ../docs/.
        cd ..
        javadoc -encoding utf8 --enable-preview --release 17 -d javadoc -sourcepath src/main/java -subpackages org org.maxicp
        cp -r javadoc docs/.
    - name: Commit the new processed data
      run: |
        git pull
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m "Update" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
